name: Build and release plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build Package
      run: |
        npm run build
        [[ ! -d bundle ]] && mkdir bundle
        pushd dist
        tar -zcvf ../bundle/codify.tar.gz ./*
        zip -r ../bundle/codify.zip ./*
        popd

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        # body_path: ...
        draft: false
        prerelease: false

    - name: Upload codify.tar.gz
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bundle/codify.tar.gz
        asset_name: codify.tar.gz
        asset_content_type: application/gzip

    - name: Upload codify.zip
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bundle/codify.zip
        asset_name: codify.zip
        asset_content_type: application/zip
